backend:
  name: github
  squash_merges: true
  repo: robert-macwha/frameworks
  branch: dev-decap-cms # Branch to update (optional; defaults to master)
  open_authoring: true

publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "articles"
    label: "Articles"
    folder: "/src"
    create: true
    nested:
      depth: 100 # max depth to show in the collection tree
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
