backend:
  name: github
  repo: robert-macwha/frameworks
  branch: dev-decap-cms
  client_id: "Ov23li2PTQXAj14bAnKJ"
  scope: "repo"
  base_url: "https://frameworks-sage.vercel.app/"
  auth_endpoint: auth
  squash_merges: true
  open_authoring: true
  local_backend: true

publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "articles"
    label: "Articles"
    folder: "/src"
    create: true
    nested:
      depth: 100 # max depth to show in the collection tree
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
