backend:
  name: git-gateway
  branch: dev-decap-cms
  squash_merges: true

publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "articles"
    label: "Articles"
    folder: "/src"
    create: true
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: "{{title}}"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true }
      - { label: "Body", name: "body", widget: "markdown" }
